/*
 *      CnvCalling.hh - this File is part of noise-free-cnv.
 *
 *      Copyright 2010-2013 Philip Ginsbach <philip.develop@gmail.com>
 *
 *      This program is free software: you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation, either version 3 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _CNVCALLINGREPORT_
#define _CNVCALLINGREPORT_
#include "CnvSequence.hh"
#include <iostream>

/* ReportEntry is a class used to represent CNVs. Objects of this class are
   being generated by the calling functions defined in the CnvCalling.hh file.

   create_report_html generates a html file that displays all the CNVs that
   the function receives as an array of ReportEntrys in a human-readable form.

   The calling part of noise-free-cnv is largely experimental and not included
   in the GUI program noise-free-cnv-gtk. */
 
namespace Cnv { namespace Call {

class ReportEntry
{
public:
	bool operator<(const ReportEntry& entr) const
		{ return start_number<entr.start_number; }

	unsigned type;

	unsigned start_number;
	unsigned end_number;

	unsigned char chromosome;

	std::string start_id;
	std::string end_id;

	unsigned start_pos;
	unsigned end_pos;

	double score_inner;
	double score_enter;
	double score_leave;
};

void create_report_html(const Sequence& seq,
	std::vector<ReportEntry>& entr, std::ostream& os);

}}

#endif
